In [ ]:
import torch

a = torch.zeros(5,2)
b = torch.ones(4,1)

# print(a + b) shape uyumsuz

c = torch.rand(5,1)
print((a + c).shape) # C'deki 1 uzatılır

x = torch.tensor([[1.,2.,3.],[4.,5.,6.]])
print(x.size())

d = torch.arange(6)
print(d.shape)
d = d.reshape(2,3)
print(d.shape)

e = torch.tensor(5.0)
print(e + e.reshape(1,1))


torch.Size([5, 2])
torch.Size([2, 3])
torch.Size([6])
torch.Size([2, 3])
tensor([[10.]])


In [ ]:
x[0] # tensor([1., 2., 3.]) shape (3,) 1D
x[:,1] # col 2
x[1,2] # row 2, col 3
x[:,:2] # col 1-2
x[0:1] # tensor([[1., 2., 3.]]) shape (1,3) 2D

tensor([[1., 2., 3.]])

In [ ]:
x.reshape(3,2)
x.reshape(-1) # tensor([1., 2., 3., 4., 5., 6.]) 1D
x.reshape(1, -1) # tensor([[1., 2., 3., 4., 5., 6.]]) 2D
x.T # Transpoz

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [ ]:
x.sum()
x.sum(dim=0) # tensor([5., 7., 9.])
x.sum(dim=1) # tensor([ 6., 15.])
x.sum(dim=1, keepdim=True) # tensor([[ 6.],[15.]]) boyut değişmedi
x.mean(dim=0) # tensor([2.5000, 3.5000, 4.5000])

tensor([2.5000, 3.5000, 4.5000])

In [ ]:
x + torch.ones(3)
x + torch.ones(2,1)
torch.ones(3,1) + torch.ones(1,4)
# x + torch.ones(2) size error
torch.ones(4,1)+ torch.ones(3)
torch.ones(5,1,3) + torch.ones(4,1)

tensor([[[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]])

In [ ]:
x @ torch.ones(3)
# x @ x - içler aynı değil
x @ x.T
x @ torch.ones(3)
torch.ones(3) @ torch.ones(3)
torch.tensor([1., 2., 3.]) @ torch.tensor([4., 5., 6.])

tensor(32.)